<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test::Unit::Result - unit testing framework helper class</title>
    <style>
        body { font-family: monospace; margin: 20px; line-height: 1.4; }
        a { color: #0066cc; }
        pre { white-space: pre-wrap; }
    </style>
</head>
<body>
    <div id="main-content">
<section class="p-strip is-bordered">
<div class="row">
<div class="col-3 u-hide--small u-hide" id="toc">
</div>
<div id="tableWrapper">
<p id="distroAndSection"></p>

Provided by: <a href="https://launchpad.net/ubuntu/questing/+package/libtest-unit-perl">libtest-unit-perl_0.27-1_all</a> <br><br><pre>
</pre><h4><b>NAME</b></h4><pre>
       Test::Unit::Result - unit testing framework helper class

</pre><h4><b>SYNOPSIS</b></h4><pre>
       This class is not intended to be used directly

</pre><h4><b>DESCRIPTION</b></h4><pre>
       This class is used by the framework to record the results of tests, which will throw an instance of a
       subclass of Test::Unit::Exception in case of errors or failures.

       To achieve this, this class gets called with a test case as argument.  It will call this test case's run
       method back and catch any exceptions thrown.

       It could be argued that Test::Unit::Result is the heart of the PerlUnit framework, since TestCase classes
       vary, and you can use one of several Test::Unit::TestRunners, but we always gather the results in a
       Test::Unit::Result object.

       This is the quintessential call tree of the communication needed to record the results of a given test:

           $aTestCase-&gt;run() {
               # creates result
               $aTestResult-&gt;run($aTestCase) {
                   # catches exception and records it
                   $aTestCase-&gt;run_bare() {
                       # runs test method inside eval
                       $aTestCase-&gt;run_test() {
                           # calls method $aTestCase-&gt;name()
                           # and propagates exception
                           # method will call Assert::assert()
                           # to cause failure if test fails on
                           # test assertion
                           # it finds this because $aTestCase is-a Assert
                       }
                   }
               }
           }

       Note too that, in the presence of Test::Unit::TestSuites, this call tree can get a little more
       convoluted, but if you bear the above in mind it should be apparent what's going on.

</pre><h4><b>AUTHOR</b></h4><pre>
       Copyright (c) 2000-2002, 2005 the PerlUnit Development Team (see Test::Unit or the <u>AUTHORS</u> file included
       in this distribution).

       All rights reserved. This program is free software; you can redistribute it and/or modify it under the
       same terms as Perl itself.

</pre><h4><b>SEE</b> <b>ALSO</b></h4><pre>
       •   Test::Unit::Assert

       •   Test::Unit::TestCase

       •   Test::Unit::Exception

perl v5.38.2                                       2024-07-27                            <u>Test::Unit::<a href="../man3pm/Result.3pm.html">Result</a></u>(3pm)
</pre>
 </div>
</div></section>
</div>
</body>
</html>